/*
 * Wipe Analytics
 * Copyright (C) TENSQUARE GmbH
 */
(function(){function ob(a,b){for(var c=-1,d=0;0<=(c=a.indexOf(b,c+1));)++d;return d}function pb(a,b){var c=a.indexOf(b,0);return 0<=c?[a.substr(0,c),a.substr(c+b.length)]:[a,""]}function y(a,b,c){return a.substring(b,void 0!==c?c:a.length)}function Pa(a,b,c){return a.length>b&&0<=b?(w(c)||(c="..."),Pa(y(a,0,b-c.length)+c,b,"")):a}function fa(a,b){return 0<=a.indexOf(b,0)}function L(a,b){return 0===a.indexOf(b,0)}function ma(a,b){var c=a.lastIndexOf(b);return 0<=c&&c===a.length-b.length}function Ha(a){return y(a,
0,1).toUpperCase()+y(a,1)}function M(a,b){a[a.length]=b}function na(a,b){for(var c,d=!1;0<=(c=oa(a,b));)a.splice(c,1),d=!0;return d}function oa(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]==b)return c;return-1}function Qa(a,b){return 0<=oa(a,b)}function db(a,b){for(var c=0,d=a.length;c<d;c++)b(a[c],c,a)}function Rb(a){for(var b,c=a.length,d;c;)d=pa(c),b=a[--c],a[c]=a[d],a[d]=b}function Ra(a,b){b=b?encodeURI:encodeURIComponent;return v(b)?b(a):escape(a)}function Sa(a){var b=decodeURIComponent;a=a.split("+").join(" ");
if(v(b))try{var c=b(a)}catch(d){}return c?c:unescape(a)}function Ta(a,b){var c=[],d;a=a.split(".");for(d=a.length;1<d--;)M(c,a.join(".")),1===d&&b&&M(c,a[0]),a.shift();return c}function Ia(a,b,c){a=parseInt(a,b||10);R(a)||(a=c||0);return a}function N(a,b){return Ia(a,10,b)}function z(a){return"undefined"!==typeof a}function A(a){return!z(a)||null===a||""===a}function F(a){return!!a&&"object"===typeof a}function v(a){return"function"===typeof a}function R(a){return"number"===typeof a&&isFinite(a)}
function w(a){return"string"===typeof a}function D(a){return a instanceof Array}function Ua(a,b){var c=b||5381;for(b=a.length-1;0<=b;b--)c=(c<<5)+c+a.charCodeAt(b);return c&2147483647}function pa(a){return Math.floor(Math.random()*(a||2147483647))}function O(){return(new Date).getTime()}function X(){return Math.floor(O()/1E3)}function qa(a,b){return a?qb?qb.call(a,b):b in a:!1}function rb(a,b){var c,d=[];for(c in a)!b&&v(a[c])||M(d,c);return d}function ra(a,b,c){if(F(a)&&F(b)){var d=c?c:rb(a);for(c=
d.length-1;0<=c;c--){var e=d[c];if(!ra(a[e],b[e]))return!1}return!0}return a===b}function Q(a,b,c,d){var e;b=b||{};if(a){if(D(c)){var f={};for(e=0;e<c.length;e++){var k=c[e];f[k]=k}c=f}e=c?c:a;for(k in e)if(qa(a,k)||c&&k in a)f=a[k],e=c?c[k]:k,d&&(e=d+e),v(f)||(b[e]=f)}return b}function Sb(a,b){var c,d={};if(a)for(c in a)if(qa(a,c)){var e=a[c];v(e)||b(c)||(d[c]=e)}return d}function eb(a,b,c){for(var d in b)if(c||!a[d])a[d]=b[d];return a}function E(a,b,c,d,e,f){var k,g=[];b||""===b||(b="&");f||""===
f||(f="=");for(var h in a)if(w(h)){var m=a[h];c&&(h=c+h);D(m)||(m=[m]);for(k=0;k<m.length;k++){var l=m[k];if(!(v(l)||!e&&F(l))){if(!z(l))if(d)l="";else continue;M(g,h+f+Ra(l,"&"!==b))}}}return g.join(b)}function ha(a,b,c){var d={},e=a?a.charAt(0):"";a=("?"===e||"#"===e?y(a,1):a).split(b||"&");b=a.length;for(e=0;e<b;e++){var f=a[e].split("=");if(f[0]){var k=f.shift();var g=f.length;c&&(k=k.toLowerCase());(g=1===g?f[0]:0<g?f.join("="):null)&&(g=Sa(g));f=d[k];z(f)&&(z(g)&&(D(f)||(f=[f]),M(f,g)),g=f);
d[k]=g}}return d}function sa(a,b,c){a=a[b];z(a)?F(a)&&z(a.enabled)&&!a.enabled&&(a=!1):a=c;return!!a}function Ja(a,b,c,d){if(sa(a,b)){var e=a[b+"Rate"];z(e)||(e=a[b]&&a[b].rate);a=N(e,c||100);d&&(d.value=a);return Math.random()<a/100}return!1}function Ka(a){return a?{trackRate:a}:void 0}function Va(a){var b=this;w(a)&&(a=ha(a));F(a)&&Q(a,b);b.toString=function(){return E(b)}}function La(a){return a&&1===a.nodeType}function Wa(a,b){return La(a)&&w(a.tagName)&&a.tagName.toLowerCase()===b.toLowerCase()}
function sb(a,b,c){var d=u.createElement("input");d.setAttribute("type","hidden");d.setAttribute("name",b);d.setAttribute("value",c);return a.appendChild(d)}function ib(){try{return p.self!==p.top}catch(a){return!0}}function tb(a,b){b=b||a.target;var c=u.createElement("a");if(F(a)&&a.href)var d=a.href;else d=a,a=c;var e=c.click;if(F(e))try{return c.href=c===a?d:a.href,b&&(c.target=b),u.body.appendChild(c),e(),!0}catch(f){}a=p;if(b){if("_blank"===b)return!1;"_top"===b?a=p.top.document:"_parent"===
b&&(a=p.parent.document)}a.location=d;return!0}function Y(a,b){var c,d=["","moz","ms","webkit"];if(a&&b){var e=Ha(b);for(c=0;c<d.length;c++){var f=(f=d[c])?f+e:b;try{if(z(a[f]))return f}catch(k){break}}}}function ub(a,b){return(b=Y(a,b))?a[b]:void 0}function vb(){var a=u.cookie;return a&&""!==a?a.split(";"):[]}function ta(a,b,c){var d=b;var e=c||{};c=e.expires;b=e.path;var f=e.domain,k=e.secure;e=e.samesite;null==d?(d="",c=-1,e=void 0):d=F(d)&&!D(d)?E(d):Ra(d,!0);a=a+"="+d;c&&(R(c)||c.toUTCString)&&
(R(c)?(d=new Date,d.setTime(d.getTime()+1E3*c)):d=c,a+="; expires="+d.toUTCString());A(b)||(a+="; path="+b);A(f)||wb(f)||(a+="; domain="+f);A(e)||(a+="; samesite="+e);A(k)||(a+="; secure");return u.cookie=a}function xb(a,b){for(var c=0,d=a.length;c<d;c++)ta(a[c],null,b)}function Tb(a){var b=this,c={},d="_wwau _wwav _wwar _wwas _wwao _wwah".split(" "),e=["_coe","_coo","_col"],f={},k={},g;b.dirty=function(){for(var a in f)if(f[a])return!0;return!1};b.get=function(a){return c[a]};b.toMap=function(a){return Q(c,
null,a||d)};b.set=function(a,d,l){d&&F(d)&&(d=d.toString(),A(d)||(d+="&v=1"));c[a]=d;l?null===d||void 0===d?b.remove(a):b.save(a):Qa(e,a)||(f[a]=!0)};b.removeAll=function(){var a;for(a=0;a<d.length;a++)b.remove(d[a])};b.remove=function(a){ta(a,null,void 0);ta(a,null,g);c[a]=void 0;f[a]=!1};b.load=function(){var a,b,e=vb();for(a=0;a<d.length;a++){var n=b=d[a];a:{var f=b;b=(b=e)||vb();var g=0;for(f+="=";g<b.length;g++){var k=b[g].replace(/^\s+/,"").replace(/\s+$/,"");if(L(k,f)){b=Sa(y(k,f.length));
break a}}b=null}c[n]=b||void 0}};b.save=function(a){var d,l={},n=b.persist;if(b.enabled){if(a){var h={};h[a]=void 0;a=[]}else h=c,a=e;l.domain=g.domain;l.path=g.path;l.samesite=g.samesite;l.secure=g.secure;for(d in h)Qa(a,d)||(l.expires=n?k[d]:null,ta(d,c[d],l),f[d]=!1)}};b.cleanup=function(a){xb(["_wwau","_wwav","_wwar"]);if(a){var b;var c=u.location;a=c.hostname;var n=c.pathname,d={};var e=wb(a)?[a]:Ta(a,0);e.push(void 0);for(c=0;c<e.length&&!((a=e[c])&&6>a.length);c++)for(b=0;0<=(b=n.indexOf("/",
b||0));){++b;d.domain=a;d.path=y(n,0,b);try{xb(["_wwau","_wwav","_wwar"],d)}catch(r){}}}};b.toString=function(){return E(c)};b.toPar=function(){return E(b.toMap("_wwau _wwav _wwar _wwah _coo _coe _col".split(" ")))};b.enabled=1;(function(a){var c=a.visitTimeout||1800,d=a.refTimeout||15768E3,n=a.domain,e=a.cookiePath,f=a.cookieSameSite;if(!f){a:{if(ib()&&(f=u.referrer)){f=(new S(f)).hostname;f=f!==p.location.hostname;break a}f=!1}f=f?"none":"lax"}A(e)&&(e="/");k._wwau=94608E3;k._wwav=c;k._wwar=d;k._wwas=
null;b.persist=z(a.persistData)?a.persistData:!0;b.enabled=z(a.useCookies)?a.useCookies:!0;g={};n&&(g.domain=n);e&&(g.path=e);f&&(g.samesite=f.toLowerCase());"none"===f&&"https:"===p.location.protocol&&(g.secure=1)})(a)}function yb(a){var b=p.JSON,c;this.get=function(a){if(c)try{var e=c.getItem(a);w(e)&&0<e.length&&b&&(e=b.parse(e));return e}catch(f){}};this.set=function(a,e){if(c)try{c.setItem(a,b?b.stringify(e):e)}catch(f){}};this.remove=function(a){if(c)try{c.removeItem(a)}catch(e){}};try{if(c=
a?p.localStorage:p.sessionStorage)this.set("waStoragewa","waStoragewa"),this.remove("waStoragewa")}catch(d){c=void 0}this.supported=!!c}function zb(){ia||(ia=new yb(0));return ia.supported?ia:void 0}function Ab(a,b){this.extract=function(b){var c={};w(b)&&(b=new S(b));b=b.getParams(!0);Q(b,c,a);return c};this.name=b||null}function S(a){var b=a,c="",d=null,e="",f="",k="",g=void 0;if(w(b)){var h=b.indexOf("://",0);0<=h&&(c=y(b,0,h+1),b=y(b,h+3),d="",h=b.indexOf("/",0),0<=h&&(d=y(b,0,h),b=y(b,h)));h=
b.indexOf("#",0);0<=h&&(k=y(b,h),b=y(b,0,h));h=b.indexOf("?",0);0<=h?(e=y(b,0,h),f=y(b,h)):e=b;""===d?(d=e,e="/"):d||(d="");var m=d=d.toLowerCase();h=m.indexOf(":",0);0<=h&&(m=y(m,0,h))}this.protocol=c;this.host=d;this.hostname=m;this.path=e;this.query=f;this.hash=k;this.getParams=function(a,b){g||(g=ha(f,"&",b));a&&(g._protocol_=c,g._host_=d,g._path_=e);return g};this.toString=function(){return a}}function wb(a){var b;if(b=w(a))b=!!a.match(/\d+\.\d+\.\d+\.\d+/);return b}function P(a,b,c){a.addEventListener?
a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function ua(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function K(a,b){return p.setTimeout(a,b)}function va(a){a&&p.clearTimeout(a)}function Ub(a,b){return p.setInterval(a,b)}function Bb(){function a(a,b){var c;if(!g[b]||3===b){g[b]=1;var e=k[b];if(D(e))for(c=0;c<e.length;c++)e[c](a,b)}}function b(){if(!g[0]&&!g[1]&&!ib()){try{var c=u.documentElement;c&&c.doScroll&&c.doScroll("left")}catch(n){600>
++m&&K(b,50);return}a({},0)}}function c(b){ua(u,"DOMContentLoaded",c);a(b,0)}function d(b){"complete"===u.readyState&&(ua(u,"readystatechange",d),a(b,0))}function e(b,c){P(p,b,function(b){a(b,c)})}var f=this,k=[],g=[],h=[],m=0;f.add=function(a,b,c,e){if(a)f.on(0,a);if(b)f.on(1,b);if(c)f.on(2,c);if(e)f.on(3,e)};f.on=function(a,b,c){var e=h[a];v(e)&&v(b)&&(k[a]||(k[a]=[],e()),c&&(c=u.readyState,c="complete"===c?0===a||1===a:"loading"!==c?0===a:!1),c?K(b,200):M(k[a],b))};h[0]=function(){u.addEventListener?
P(u,"DOMContentLoaded",c):u.attachEvent&&(P(u,"readystatechange",d),b())};h[1]=function(){e("load",1)};h[2]=function(){e("unload",2)};h[3]=function(){e("beforeunload",3)}}function Vb(a){function b(){var a=pa(1073741824),b=pa(536870912),c=O()&65535;b=("00000000"+(b&4294901760|c)).slice(-9);return a+b}function c(a){if(!k){var b=f;b=""+b;"-"===b.charAt(0)&&(b=y(b,1));var c=b.length-9;b=0<c?[y(b,0,c),y(b,c)]:["",b];k=(N(b[0])||0).toString(36)+"-"+(N(b[1])||0).toString(36)}b=k;a&&(g||(g=Cb(k).toString(36)),
b+="-"+g);return b}function d(a){if(w(a))d(ha(a));else if(F(a)){f=a.id;if(w(a.ti)){var b=a.ti.split(",");for(var c=0,g=b.length;c<g&&A(b[c]);)b.shift();for(c=b.length-1;0<=c&&A(b[c]);)b.pop()}else b=D(a.ti)?a.ti:[];h=b;m=N(a.c);e.attr=a.at}}var e=this,f=void 0,k,g,h=[],m=0;e.getID=function(){return f};e.setID=function(a){f=a};e.getXI=function(a){a="xi.1-"+c(!0)+"."+(a||X()).toString(36);var b=h.length;1<m&&1<b&&(b=N(h[b-2]),0<b&&(b=Math.round(b/1800).toString(36),a+="."+m+"-"+b));return a};e.getSI=
function(a){return"si.1-"+c(!1)+"."+(a||0).toString(36)};e.addVisit=function(a){a=a||X();m++;M(h,a);3<h.length&&h.shift()};e.toString=function(){return E({id:f,c:m,ti:h,at:e.attr})};e.attr=void 0;A(a)?f=b():d(a)}function jb(a){return w(a)&&fa(a,"_wxi")?ha(a)._wxi:void 0}function Cb(a){a=Ua(a+"");if(!wa){var b=T||{};b=[b.userAgent,b.platform,b.language].join("|");wa=Ua(b)}return(wa&32767)<<16|a&65535}function Wb(a,b){function c(a){e=b||X();k=f=0;g=e;w(a)?c(ha(a)):F(a)&&(e=N(a.ti,e),f=N(a.pc),k=N(a.ec),
g=N(a.le,g))}var d=this,e,f,k,g;d.addPV=function(){g=X();return 500>=++f};d.addEv=function(){g=X();return 500>=++k};d.toString=function(){return E({ti:e,pc:f,ec:k,le:g,at:d.attr},"&",void 0,0,1)};c(a);d.ti=e;d.attr=void 0}function Db(a){var b=this;b.ti=a||X();b.toString=function(){return b.ti+""}}function Xb(a,b){function c(a,b,c){var e=A(a)?"":a.charAt(a.length-1);c!==e&&"&"!==c&&fa(a,c)&&(c="&");return a+(e!==c&&"&"!==e?c:"")+b}function d(a,b){var e="_wxi",d=n(),f=-1,g="#"===(b||"?"),k;e+="=";d=
d?e+d:"";for(a||(a="");0<=(f=a.indexOf(e,f+1||0));)if(0<f&&fa("?&#",a.charAt(f-1))){var l=a.indexOf("#",0);var h=0<=l&&f>l;var m=g!==h;b=a.indexOf("&",f||0);(k=A(d)||m)&&0<b&&++b;k=0;0<l&&!h&&b>l?(b=l,k=1):0>b&&(b=a.length,k=1);k&&(m||A(d))&&--f;a=y(a,0,f)+(m?"":d)+y(a,b);m||(d="")}A(d)||(l=a.indexOf("#",0),a=g?0>l?a+("#"+d):c(a,d,"#"):0>l?c(a,d,"?"):c(a.substring(0,l),d,"?")+a.substring(l));return a}function e(a,b){var c=a.href||a.action;if(w(c))if(a.href)a.href=d(c,b);else{var e=a.method;if(w(e))if(e=
e.toLowerCase(),"get"===e){c=a.childNodes||[];for(b=0;b<c.length;b++)if("_wxi"===c[b].name){c[b].setAttribute("value",n());return}sb(a,"_wxi",n())}else"post"===e&&(a.action=d(c,b))}}function f(a,b,c){if(b&&(c||a!==u.location.hostname))for(c=0;c<b.length;c++){var e=b[c];if(e instanceof RegExp){if(e.test(a))return!0}else if(ma(a,e))return!0}return!1}function k(a){try{var b;a=a||p.event;var c=a.target||a.srcElement;for(b=0;c&&50>b;b++){if(c.href&&Qa(r,c.nodeName.toLowerCase())){var d=c;break}c=c.parentNode}d&&
d.protocol&&L(d.protocol,"http")&&f(d.hostname,q)&&e(d,Ya)}catch(Bc){}}function g(a){try{var b;a=a||p.event;var c=a.target||a.srcElement;(b=/^https?:\/\/([^\/:]+)/.exec(c.action))&&f(b[1],q)&&e(c,Ya)}catch(W){}}function h(a){try{var c;a=a||p.event;var e=a.data;if(w(e))if(Z&&"wa:getXI"===e){var d=c=a.origin;var g=H;g||(d=(new S(c)).hostname,g=q||[]);f(d,g,!0)&&a.source.postMessage("wa:_wxi="+n(),c)}else Z&&L(e,"wa:rcv_wxi=")?b&&b(y(e,11)):V&&L(e,"wa:_wxi=")&&(e=y(e,8),v&&v(e),a.source.postMessage("wa:rcv_wxi="+
e+";"+p.location.host,"*"))}catch(Cc){}}function m(a){var b=D(a)?a:void 0;l(!1,!1,!1,!0);if(Z=!0===a||b&&b.length)H=b,t||l(!0,!1,!1,!0)}function l(a,b,c,e){var d=a?P:ua;b&&(x=a,d(u,"mousedown",k),d(u,"touchstart",k),d(u,"keyup",k));if(c)for(c=u.forms,b=0;c&&b<c.length;b++)d(c[b],"submit",g);e&&(t=a,d(p,"message",h))}function n(){return a().getXI()}var x,t,r,q,H,Ya,Z,V,v;this.url=d;this.enable=e;this.autoEnable=function(a){r=a.elements||["a"];D(r)||(r=r.split(","));var b=na(r,"iframe");var c=na(r,
"form");(q=a.targets)&&!D(q)&&(q=[q]);Ya=a.paramDest;l(!0,!x,c);a=a.viaMessage;z(a)||(a=b);m(a)};this.xdm=m;this.rqxi=function(a,b,c){b=b||p.parent;V=a&&b&&b!==p.self;v=a;V&&(t||l(!0,!1,!1,!0),b.postMessage("wa:getXI",c||"*"))};this.ue=function(){l(!1,!0,!0,!0)};this.xi=n}function Eb(a,b,c,d){function e(){g.rt="-";g.src=void 0;g.med=void 0;g.el=void 0;g.kw=void 0;g.cid=void 0;g.cna=void 0}function f(a,b){e();if(!A(a))if(a=new S(a),0===b){a:{for(b=0;b<aa.length;b++){var c=aa[b];var d=c.extract(a);
d=Q(d,null,m);if(d.cna||d.cid){Q(d,g);g.intf="par-"+c.name;a=!0;break a}}a=!1}a&&(g.rt="c")}else 2===b&&(!A(c=Fb.get(a))&&c.v?(g.rt="s",g.src=c.k,g.kw=c.v):(g.rt="r",g.src=a.host,g.el=a.path+(l[h]?a.query:"")))}function k(a){var b=rb(g);a||(a=oa(b,"ti"),0<=a&&b.splice(a,1));return b}var g=this,h="track"+Ha("query"),m=void 0,l=d||{};g.ti=c||X();g.equals=function(a){var b=k(!1);return ra(g,a,b)};g.toString=function(){return E(g)};g.get=function(){return a};g.set=function(a,b){e();a&&(z(b)?f(a,b):(w(a)&&
(a=ha(a)),Q(a,g,k(!0))))};g.gettype=function(){return g.rt};(function(a,b){m={};a&&f(a,b)})(a,b)}function Zb(){function a(d){var e,f;if(w(d))return a(new S(d));if(d instanceof S){a:{var k=d.host;var g=Ta(k.toLowerCase(),1);for(e=g.length-1;0<=e;e--){k=g[e];var h=b[k];h||(k=c[k],h=b[k]);if(h){k={k:k,v:h};break a}}k=null}if(k){e=d.getParams(!1,!0);h=k.v;D(h)||(h=[h]);for(d=0;d<h.length&&!(f=e[h[d].toLowerCase()]);d++);return{k:k.k,v:f}}}return null}var b={"1und1":"su",allesklar:"words",altavista:"q",
aol:["q","query","encquery"],arcor:"Keywords",ask:"q",bing:"q",freenet:"query",google:"q",live:"q",lycos:"query",meinestadt:"words",metager:"eingabe",msn:"q",search:"q",suchen:"what",web:"su",yahoo:"p"},c={"meta.rrzn.uni-hannover.de":"metager"};this.get=function(b){return a(b)};this.add=function(a,c){b[a]=c};this.addAlias=function(a,b){c[b]=a};this.clear=function(){b=c={}}}function Gb(a){function b(a,b,c){var e=h.hostname,d="-";A(e)||(d=a.toString(),L(b,".")&&(b=y(b,1)),ma(e,b)&&(A(c)||L(a.path,c))&&
(d="(self)"));return d}var c=this,d=u.referrer,e=a.ignoredRef,f=a.cookiePath||"/",k=u.location;c.title=a.logPageTitle?u.title:void 0;var g=k.hostname.toLowerCase();c.host=g;c.path=k.pathname;c.query=k.search;c.chs=(u.characterSet||u.charset||"-").toLowerCase();c.id=pa();if(A(d))d="-";else{var h=new S(d);k=h.hostname;d="-";k&&g&&(k!==g?(a=a.domain||u.domain||g,d=b(h,a,f),D(e)&&0<e.length&&Qa(e,k)&&(d="-")):d="(self)")}c.ref=d;c.toString=function(){return E(c,"&","di",0,1)}}function $b(a){var b=this,
c="-",d="-",e,f,k,g,h;a||(a={logFlash:1});b.collect=function(){var m;if(I){var l=I.colorDepth||I.pixelDepth;var n=p.devicePixelRatio;if(m=I.logicalXDPI){var x="-l"+m+"-d"+I.deviceXDPI;(m=I.systemXDPI)&&(x+="-s"+m)}e=I.width+"x"+I.height;l&&(e+="x"+l);n&&(e+="xr"+n);x&&(e+="xd"+x);l=void 0;n=I.orientation;n||(n=(n=Y(I,"orientation"))?I[n]:p.orientation);F(n)&&(l=n.angle,n=n.type);w(n)?(m=fa(n,"portr")?"p":"l",n=m+=fa(n,"sec")?"s":"p"):R(n)&&(l=n,n=I.width>I.height?"l":"p");n&&R(l)&&(n+=""+l);(l=n)&&
(e+="xo"+l);I.isExtended&&(e+="xe1");(l=I.availWidth)&&(f=l+"x"+I.availHeight);var t;if(l=p.innerHeight?{w:p.innerWidth,h:p.innerHeight,ow:p.outerWidth,oh:p.outerHeight}:(z(t=u.documentElement)||z(t=u.body))&&t.clientHeight?{w:t.clientWidth,h:t.clientHeight}:null)k=l.w+"x"+l.h,l.ow&&(k+="-"+l.ow+"x"+l.oh)}var r;if(a.logFlash){var q;if((l=T?T.plugins:void 0)&&0<(q=l.length))for(t=0;t<q&&!r;t++)n=l[t],0<=n.name.indexOf("Shockwave Flash")&&(r=n.description.split("Shockwave Flash ")[1]);else for(q=[7,
6,void 0],t=0;t<q.length&&!r;t++){r=void 0;l=q[t];n=void 0;try{r=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"+(l?"."+l:"")),6===l&&(n="X 6,0,21,0",r.AllowScriptAccess="always"),n=r.GetVariable("$version")}catch(Yb){}n&&(n=n.split(" ")[1]);r=n}if(r)for(r=r.replace(/[,r]/g,".").replace(/ /g,"");2<ob(r,".");)r=y(r,0,r.lastIndexOf("."));else r="-"}else r=void 0;c=r;d=T&&T.javaEnabled()?1:0;r=(T.language||T.browserLanguage||"-").toLowerCase();if(q=T.languages)for(t=q.slice(0),4<t.length&&(t.length=
4),q=0;q<t.length;q++)t[q]=t[q].toLowerCase();else t=[];r&&(q=oa(t,r),0<q&&(t.splice(q,1),q=-1),0>q&&4<t.unshift(r)&&(t.length=4));g=t.join(".");a:{var H;try{var Ya=T.hardwareConcurrency||"";var Z=T.deviceMemory||"";var V=(H=Y(T,"maxTouchPoints"))?T[H]:0;var v=0<V||"ontouchstart"in p;h=["c"+Ya,"m"+Z,"t"+(v?1:0),"tp"+(V||0)].join("_");break a}catch(Yb){}h=void 0}return b};b.toString=function(){return E({scr:e,dsk:f,win:k,lan:g,hdw:h,fla:c,jae:d},"&","ci")}}function ac(){this.check=function(a){(new Bb).on(0,
function(){var b=u.createElement("div");b.innerHTML="&nbsp;";b.className="ad-img";u.body.appendChild(b);K(function(){a(0>=b.offsetHeight)},750)},!0)}}function bc(a){a=a||p.console;this.log=function(b){var c=ba._DEBUGGER_;c=c?c.log:void 0;v(c)?c(b):a&&v(a.log)&&a.log(ca+": "+b)}}function Hb(a){function b(b,c){v(a)&&a(b);v(c)&&c()}function c(b,c){var e=new Image(1,1);e.onload=e.onerror=c||function(){};e.src=a+"?"+b}var d=v(a)?b:c;this.log=function(a,b){if(F(a))a=E(a);else if(!w(a))return!1;d(a,b);return!0}}
function Ib(a){function b(a,b,c){a.log(b,c?function(){c.done(a)}:void 0)}var c=this,d=[];c.add=function(a){a instanceof Hb?M(d,a):D(a)?db(a,c.add):(w(a)||v(a))&&c.add(new Hb(a))};c.log=function(a,f){var e;if(c.enabled)for(v(f)&&(e=new cc(d,f)),f=0;f<d.length;f++)b(d[f],a,e)};c.enabled=1;a&&c.add(a)}function cc(a,b){var c=a.slice(0);this.done=function(a){na(c,a);0===c.length&&b()}}function dc(a,b,c,d,e){this.toString=function(){var f={t:a.toString(),n:b};c&&F(c)?Q(c,f,void 0,"i."):f.i=c;d&&F(d)?Q(d,
f,void 0,"v."):f.v=d;e&&(z(e.isInteraction)&&(f.x=e.isInteraction?1:0),z(e.trackRate)&&(f.r=e.trackRate));return E(f,"&","ev")}}function ec(a,b,c,d){function e(a){var b,c="",e;for(b=0;b<a.length;b++)(e=a[b])&&e.toPar?c+=e.toPar()+"&":A(e)||(c+=e+"&");return c}function f(){return[]}var k=this;k.log=function(f,h,m,l,n){h=new dc(k,f,h,m,l);f=c(a,f);if(!d||d())f[f.length]=h,b.log(e(f),n)};k.toString=function(){return a};v(c)||(c=f)}function fc(a){this.toString=function(){return E({id:a},"&","ac")}}function xa(a,
b){var c;if(b)for(c in b)if(L(a,c)){a=b[c]+y(a,c.length);break}return Ha(a).replace(/[a-z]/g,"").toLowerCase()}function ja(a,b){var c=p.PerformanceObserver,d=a.type,e=!!a.buffered;a=R(a.threshold)?a.threshold:void 0;try{if(v(c)){var f=new c(b);z(a)?f.observe({type:d,buffered:e,durationThreshold:a}):f.observe({type:d,buffered:e});return f}}catch(k){}}function ya(a,b,c){a&&(b&&(b=a.takeRecords(),v(c)&&c(b)),a.disconnect())}function gc(a){function b(){var a,b=0,m={};if(c){for(a in c){var l=c[a];if(R(l)&&
0!==l){var n=xa(a,k);m[n]=l;if(0===b||l<b)b=l}}for(a in m)m[a]-=b;0!==b&&(m.b=b);d.supported&&Q(d.get(),m,void 0,"pt");e.supported&&Q(e.get(),m,void 0,"rv");f.supported&&m.lee&&Q(f.get(),m,void 0,"m")}else(a=p.external||p["gtb"+Ha("external")])&&(l=a.pageT),l?n="gtb":(a=p.chrome)&&v(a.csi)&&(n="chr",(a=a.csi())&&(l=a.pageT)),a=R(l)?{ti:O()-Math.floor(l),src:n}:void 0,a&&(m.b=a.ti,m.ns=0,m.nssrc=a.src);return m}var c=(Za||{}).timing,d=new hc(a),e=new ic(a),f=new jc,k={red:"reD",req:"reQ",domain:"dNS"};
this.supported=!!c;this.get=b;this.toString=function(a){a||(a=b());return E(a,".",void 0,0,0,"")}}function kc(a,b,c,d,e){function f(a){z(r)&&(r=va(r));r=K(g,a)}function k(){H&&!z(r)&&f(100)}function g(){var b,d,k;z(r)&&(r=va(r));var g=n.get();var l=g.b||e;x&&(q&&(g.dcles=q-l),H&&(g.les=H-l),t&&(b=t.get("_wah.wu")))&&(t.remove("_wah.wu"),(d=u.referrer)&&d===b.url&&(d=b.ti,R(d)&&(g.lues=d-l,g.luepi=b.pid)));(b=e)&&(g.ldl=b-l);g.wai=A;d={};for(k in g)if(b=g[k],!z(D[k])||W[k]&&b!==D[k])D[k]=d[k]=b;d.v=
4;Z&&(d.lep=O()-l);x&&(d.legacy=1);l=n.toString(d);c.log("page",a,l,F);H?E&&(E.log(g.les),E=void 0):4>=++v&&(Z=1,w+=1E3,V+=w,f(V))}function h(){q=O();f(1E3)}function m(){Z=0;H=O();x?g():f(500)}function l(b,c){if(!p||3===c)if(p=1,t&&(c=u.location.href))b=c.indexOf("#",0),0<b&&(c=y(c,0,b)),t.set("_wah.wu",{ti:O(),url:c,pid:a})}var n,x,t,r,q,H,p,Z=1,V=2E3,w=0,v=0,A,D={},W={ptlcp:1,ptcls:1,rvinp:1},F=Ka(b),E;(function(){e||(e=O());n=new gc(k);x=!n.supported;t=zb();A=Jb;!x&&.5>Math.random()&&(E=new lc(a,
Math.round((b||100)/2),c));var f=x?l:void 0;d.on(0,h,!0);d.on(1,m,!0);d.on(2,f);d.on(3,f)})()}function mc(){function a(e,f){var k;e=e||{};if((k=f?ub(f,"performance"):c)&&b.supported){var g=k[d]();for(k=0;k<g.length;k++){var h=g[k];if("resource"===h.entryType){var m=h.name;h=h.duration;if(m&&L(m,"http")&&h){var l=new S(m);var n=l.host;A(n)||((m=e[n])||(m=e[n]=[]),h={u:l,d:Math.round(h)},f&&(h.f=f.location),m.push(h))}}}if(!f&&(f=p.frames))for(k=0;k<f.length;k++)try{a(e,f[k])}catch(x){}}return e}var b=
this,c=Za,d=c?Y(c,"getEntries"):void 0;b.get=function(b){var c,d=function(a,b){return b.d-a.d},e=[],h={};var m=Math.max(1E3,Math.round((b||0)/5));var l=a();for(q in l){var n=l[q];if(D(n)){var x=n.length;for(b=c=0;b<x;b++){var t=n[b];var r=t.d;c+=r;r>=m&&M(e,t)}h[q]="n"+x+".d"+c;1<x&&(n.sort&&n.sort(d),c=n[0].d,r=n[x-1].d,2<x?(b=x>>1,t=n[b].d,0===(x&1)&&(t=Math.round((t+n[b-1].d)/2))):t="",h[q]+=".dmmm"+r+"-"+t+"-"+c)}}if(x=e.length)for(2<x&&(x=2,Rb(e),e=e.slice(0,x)),b=0;b<x;b++){t=e[b];h["$sr"+b+
".d"]=t.d;var q=t.u.toString();250<q.length&&(q=y(q,0,247)+"...");h["$sr"+b+".u"]=q}return h};b.supported=!!d}function lc(a,b,c){var d=new mc;d.supported||(d=void 0);this.log=function(e){d&&(e=d.get(e),A(e)||c.log("pageel",a,E(e),Ka(b)))}}function hc(a){function b(){m=ya(m,!0);h=ya(h)}var c=this,d=Za,e=d?Y(d,"getEntriesByType"):void 0,f,k,g=0;var h=ja({type:"largest-contentful-paint"},function(b){var c=b.getEntries();b=c.length;0<b&&(b=c[b-1],f=Math.round(b.renderTime||b.loadTime),a&&a())});var m=
ja({type:"layout-shift"},function(b){k||(k=0);var c,d=k,e=b.getEntries();for(c=0;c<e.length;c++)b=e[c],b.hadRecentInput||(k+=b.value,++g);k!==d&&a&&a()});(new kb).on($a,function(){b()},!0);K(b,6E4);c.supported=!!e;c.get=function(){var a,b,h=void 0;if(c.supported){h={};if(b=d[e]("paint"))for(a=0;a<b.length;a++){var m=b[a];var r=m.name;m=m.startTime;if(R(m)&&m&&r){var q=r.split("-");for(r=0;r<q.length;r++)q[r]=Ha(q[r]);r=xa(q.join(""));h[r]=Math.round(m)}}z(f)&&(h.lcp=f);z(k)&&(h.cls=g+"-"+Math.round(1E5*
k))}return h};c.off=b}function nc(){function a(){ya(f,!0)}var b=0,c=Infinity,d=0,e=p.PerformanceObserver,f;"interactionCount"in p.performance||(f=ja({type:"event",threshold:0},function(a){a=a.getEntries();db(a,function(a){a.interactionId&&(c=Math.min(c,a.interactionId),b=(d=Math.max(d,a.interactionId))?(d-c)/7+1:0)})}));K(a,12E4);this.get=function(){return e?b:p.performance.interactionCount||0};this.off=a}function ic(a){function b(){t=ya(t);h=ya(h,!0,function(a){r(a)})}function c(){if(0!==m.length){var a=
n.get();return m[Math.min(m.length-1,Math.floor(a/50))]}}function d(a){var b=m[m.length-1],c=l[a.interactionId];if(10>m.length||a.duration>b.latency||c)c?(c.performanceEntries.push(a),c.latency=Math.max(c.latency,a.duration)):(a={id:a.interactionId,latency:a.duration,performanceEntries:[a]},l[a.id]=a,m.push(a)),m.sort(function(a,b){return b.latency-a.latency}),m.splice(10).forEach(function(a){delete l[a.id]})}var e=this,f,k,g=p.PerformanceEventTiming&&"interactionId"in PerformanceEventTiming.prototype,
h,m=[],l={},n,x;var t=ja({type:"first-input"},function(b){var c=b.getEntries();b=c.length;if(0<b){var e=c[b-1];b=Math.round(e.processingStart-e.startTime);b!==f&&(f=b,k=e.name,h&&(b=!m.some(function(a){return a.performanceEntries.some(function(a){return e.duration===a.duration&&e.startTime===a.startTime})}))&&d(e),a&&a())}});var r=function(b){b=D(b)?b:b.getEntries();var e=!1;db(b,function(a){a.interactionId&&(e=!0,d(a))});(function(){if(!a||!e)return!1;var b=c();return z(b)?z(x)?b.latency!==x.latency:
!0:!1})()&&a()};(h=g&&ja({type:"event",threshold:0},r))&&(n=new nc);(new kb).on($a,function(){b();a()},!0);K(b,12E4);e.supported=!!t||!!h;e.get=function(){var a=void 0,b,d;if(e.supported&&(a={},z(f)&&(w(k)?a.fid=f+"-"+k:a.fid=f),x=b=c(),z(b))){for(d=0;d<b.performanceEntries.length;d++)if(null!==b.performanceEntries[d].target){var g=b.performanceEntries[d];break}z(g)?a.inp=b.latency+"-"+(new Kb(g.target)).getElementXPath(!0):a.inp=b.latency}return a};e.off=b}function jc(){var a=p.console||{},b=(Za||
{}).memory||a.memory,c={js:"JS"};this.supported=!!b;this.get=function(){var a,e=void 0;if(b)for(a in e={},b){var f=b[a];if(R(f)){var k=xa(a,c);e[k]=f>>10}}return e}}function oc(a,b){var c=this;c.t=a||"js";c.ti=b||O();c.v=1;c.eq=function(a){for(var b in c)if(a&&"id"!==b&&"ti"!==b&&"cnt"!==b&&!v(c[b])&&c[b]!==a[b])return!1;return!!a}}function Lb(){function a(a){if(a&&100>e.length){a:{var b;for(b=0;b<e.length;b++)if(e[b].eq(a)){e[b].cnt=(e[b].cnt||1)+1;break a}M(e,a)}if(d.on)d.on(a)}}function b(a,b){return Q(a,
b,{category:"t",message:"msg",severity:"lv",filename:"src",lineno:"lno",colno:"cno",fileName:"src",lineNumber:"lno",columnNumber:"cno",url:"url",status:"sc",src:"src"})}function c(a){if(a){var c=a.target;var d=new oc;b(a,d);c&&(d.src||d.url||!c.src||(d.src=c.src),w(c.tagName)&&(d.el=c.tagName.toLowerCase()));a=a.error||a;d.st=a.stack;!d.msg&&w(a.message)&&(d.msg=a.message);return d}}var d=this,e=[];d.oe=function(b){(b=c(b))&&a(b)};d.oae=function(b){if(b=c(b))b.auto=!0,a(b)};d.tr=b;d.el=e}function Mb(a,
b){function c(a){return F(a)?!1!==a.enabled:!!a}function d(a){!k&&p.XMLHttpRequest&&(k=p.XMLHttpRequest.prototype);k&&c(a)?g||(g=k.open,k.open=function(a,b){this&&(P(this,"readystatechange",e),g.apply(this,arguments),this._url=b)}):g&&(k.open=g,g=void 0)}function e(b){var c=this||b&&b.target||{};4===c.readyState&&(b=c.status,c=c.responseURL||c._url,400<=b&&c&&a({category:"http.xhr",url:c,status:b}))}function f(e){b=e||{};!0===b&&(b={all:!0});e=b.js||b.all;c(e)?h||(h=e.observe||p,P(h,"error",a)):h&&
(ua(h,"error",a),h=void 0);d(b.http||b.all)}var k,g,h;this.upd=f;f(b)}function pc(a,b,c,d,e,f){function k(a,b,c){var e,f;D(b)||(b=[b]);for(e=0;e<b.length;e++){var g=b[e];if(w(g)||g instanceof RegExp)g={},g[c||"message"]=b[e];g=d.tr(g);var k=!1;var n=!0;for(f in g){var h=g[f];n=qa(a,f)?a[f]+"":"";k=!0;if(h instanceof RegExp)n=h.test(n);else{h+="";var l=h.length,m=L(h,"*"),x=ma(h,"*");n="*"===h?!0:m?x?fa(n,y(h,1,l-1)):ma(n,y(h,1)):x?L(n,y(h,0,l-1)):n===h}if(!n)break}if(k&&n)return!0}return!1}function g(a){(0>
r||l<r)&&(0>q||t<q)&&(n||(n=K(h,f.interval||2E3)))}function h(){var d,e;n=void 0;for(e=Ka(b);0<x.length&&(0>r||l<r)&&(0>q||t<q);){var g=d=x.shift();++l;m.set("_wah.ec",++t);g.id=t;g=void 0;var h=d.t||"";h=pb(h,".")[0];if(d.auto&&!(!0===f.auto||f.auto&&sa(f.auto,h))||f.include&&!k(d,f.include)||f.exclude&&k(d,f.exclude))d=void 0;else for(g in d.st&&!Ja(f,"stack",10)&&(d.st=void 0),h={st:2048,msg:1024,url:1024},h)w(d[g])&&(d[g]=Pa(d[g],h[g]));d&&c.log("error",a,d,e)}}var m=zb(),l=0,n;f=f||{};!0===f&&
(f={auto:!0});d=d||new Lb;var x=d.el;e?e.upd(f.auto):e=new Mb(d.oae,f.auto);var t=N(m.get("_wah.ec"));var r=f.max||10;var q=f.sessionMax||20;this.off=function(){e.upd({})};this.im=k;d.on=g;x.length&&g()}function za(a,b){var c=this;c.x=a;c.y=b;this.toString=function(){return c.x+"."+c.y}}function Kb(a){function b(a,b,c,g){a=a.toLowerCase();g&&(a=d[a]||a);if(c){if(b)if(g){"id"===b&&(b="!");var e=b+"~"+c+"~"}else e="@"+b+"='"+c+"'";else e=c;e=g?"("+e+")":"["+e+"]"}e&&(a+=e);return a}var c=a,d={html:"H",
document:"D",body:"B",div:"V",img:"M",table:"T",tbody:"Y",tr:"R",th:"Q",td:"C",form:"F",input:"I",button:"N",ul:"U",ol:"O",li:"L"};this.getElementXPath=function(a){var d,e,g=a?"_":"/";for(d=[];c&&1===c.nodeType;c=c.parentNode){var h=c.tagName;if(A(c.id)){var m=1;for(e=c;null!=(e=e.previousSibling);)e.tagName===h&&m++;if(1===m)for(m=void 0,e=c;null!=(e=e.nextSibling);)if(e.tagName===h){m=1;break}d.unshift(b(h,void 0,m,a))}else return d.unshift(b(h,"id",c.id,a)),d.join(g)}return d.length?g+d.join(g):
""};this.getElementPosition=function(){var a=0,b=0;if(c&&c.offsetParent){do a+=c.offsetLeft,b+=c.offsetTop;while(null!=(c=c.offsetParent))}return new za(a,b)}}function qc(a,b,c){function d(b){var d,e,f=O();if(!k){if(b=b||p.event)(e=b.which||b.button)&&1!==e||(d=b.target||b.srcElement);if(d&&!(1E3>f-h)){h=f;3===d.nodeType&&(d=d.parentNode);try{a:{if(z(b.pageX)){var m=b.pageX;var r=b.pageY}else if(z(b.clientX)){m=b.clientX;r=b.clientY;var q=u.documentElement?u.documentElement:u.body;m+=q.scrollLeft;
r+=q.scrollTop}else{var H=void 0;break a}H=new za(m,r)}if(H){var w=new Kb(d);var y=w.getElementPosition();var v=new za(H.x,H.y);v.x-=y.x;v.y-=y.y;var A=new za(d.offsetWidth,d.offsetHeight);var D="1-"+H+"-"+w.getElementXPath(!0)+"-"+A+"-"+v;c.log("click",a,D,g)}}catch(Ac){}}}}function e(){k=1}function f(){k&&K(function(){k=0},20)}var k,g=Ka(b),h=0;this.init=function(){P(u,"mousedown",d);P(p,"blur",e);P(p,"focus",f)}}function rc(a,b,c){function d(a){a=O();if(m&&(va(m),l&&5E3<a-l)){l=a;e();return}l=
l||a;m=K(e,1E3)}function e(){var b=u.body;var d=u.documentElement;var e=Math.max(d.clientWidth||0,p.innerWidth||0);var f=Math.max(d.clientHeight||0,p.innerHeight||0);if(void 0!==p.pageYOffset){var q=p.pageXOffset;var w=p.pageYOffset}else q=(d||b.parentNode||b).scrollLeft,w=(d||b.parentNode||b).scrollTop;var v=Math.max(b.scrollWidth,b.offsetWidth,d.clientWidth,d.scrollWidth,d.offsetWidth);b=Math.max(b.scrollHeight,b.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight);q={x:q,y:w,vw:e,vh:f,pw:v,
ph:b,scx:(q+e)/v,scy:(w+f)/b};h&&ra(q,h)||(c&&200>=++k&&c.log("scroll",a,"1-vi-"+q.x+"-"+q.y+"-"+q.vw+"-"+q.vh+"-"+q.pw+"-"+q.ph,g),h=q);l=m=void 0}function f(a,b){var c=a.clientHeight,d;(function H(){d=a.clientHeight;c!==d&&b(d);c=d;a.heightChangeTimer&&clearTimeout(a.heightChangeTimer);a.heightChangeTimer=setTimeout(H,1E3)})()}var k=0,g=Ka(b),h,m,l;this.init=function(){P(p,"scroll",d);P(p,"resize",d);P(u,"resize",d);if(p.ResizeObserver){var a=new ResizeObserver(function(a){d()});a.observe(u.body)}else f(u.body,
d)}}function sc(a,b){function c(c,d,e){var g=new f(function(e,f){e.forEach(function(e){e.isIntersecting&&(b.log("elview",a,{el:c,name:d,v:1},void 0),f.disconnect())})},{threshold:e||.5});document.querySelectorAll(c).forEach(function(a){g.observe(a)})}function d(c,d){document.querySelectorAll(c).forEach(function(e){P(e,"click",function(e){b.log("elclick",a,{el:c,name:d,v:1},void 0)})})}var e=this,f=p.IntersectionObserver,k=!!f;e.mon=function(a){var b;if(k)if(D(a))a.forEach(e.mon);else{var f=a.element;
var g=a.name;a=a.on;f&&a&&(D(a)||(a=[a]),a.forEach(function(a){b=a&&a.event||"";switch(b){case "view":c(f,g,a.threshold);break;case "click":d(f,g)}}))}};e.supported=k}function kb(){function a(){return k?u[k]:void 0}function b(){var b=a();return b?L(b,"vis"):!0}function c(c){if(c){var d,e=a(),f=b();for(d=0;d<c.length;d++){var g=c[d];v(g)&&g(f,e)}}}function d(a){c(g[a]);c(h[a]);h[a]=[]}function e(){var a=b();d(Nb);d(a?Ob:$a)}function f(a,b){var c;for(c=0;c<a.length;c++){var d=a[c];D(d)&&na(d,b)}}var k,
g=[],h=[];if(k=Y(u,"visibilityState")){var m="";if(!L(k,"visibility")){var l=k.search(/[A-Z]/);0<l&&(m=y(k,0,l))}P(u,m+"visibilitychange",e)}this.supported=!!k;this.get=a;this.vis=b;this.on=function(a,b,c){var d=c?h:g;(c=d[a])||(c=d[a]=[]);M(c,b)};this.off=function(a){a?(f(g,a),f(h,a)):g=h=[]}}function tc(a){function b(a){return w(a)&&0<=a.indexOf("_")?a.replace(/_/g,"%5F"):a}function c(b,c,d,e,g){var k=!0;if(d){c&&""!==c&&(b+=":"+c);var h=d,l=h.itd,n=l.length;if(1>=n||f(l,0,1200,7)===n)d=0<n?[h]:
[];else{c=[];for(d=0;d<n;){var m=f(l,d,1200,7);0===m&&(m=1);var r=eb({},h);r.itd=l.slice(d,d+m);d+=m;c.push(r)}h=c.length;for(d=0;d<h;d++)c[d].itpart=""+(d+1)+"_"+h;d=c}for(c=0;c<d.length;c++)a.log(b,d[c],e,g)||(k=!1)}return k}function d(a,b,d,f){a?c("view",b||"page",k(a),d,f):0===arguments.length&&e()}function e(){var a,b=m.get();for(a in b)d(b[a],a,m.attr(a));m.clear();h&&(h=va(h))}function f(a,b,c,d){var e,f=a.length,g=0;for(e=b;e<f;e++)if(g+=a[e].length+d,g>c)return e-b;return f}function k(a){var c,
d;var e={};var f=[],h=0,k={};if(a){D(a)||(a=[a]);var l=a.length;for(c=0;c<l;c++){w(a[c])&&(a[c]=ha(a[c]));var m=a[c];for(v in m)if(e[v]||(e[v]=1,f[h++]=v),d=g[v]){var p=m[v];w(p)&&p.length>d&&(m[v]=y(p,0,d-3)+"...")}}k.itv=1;k.itc=l;k.itf=f.join("_");var u=k.itd=[];for(c=0;c<l;c++){m=a[c];e=[];for(d=0;d<h;d++){var v=f[d];p=m[v];e.push(z(p)?b(p):"")}u.push(e.join("_"))}return k}}var g={na:50},h,m=new uc;this.logView=d;this.logAction=function(a,b,d,e){return a?c("action",b,k(a),d,e):!0};this.addItems=
function(a,b){m.add(a,b);h||(h=K(e,1E3))};this.setItems=function(a,b){m.set(a,b);h||(h=K(e,1E3))};this.buf=m}function uc(){var a=this,b={},c={};a.get=function(a){return 0<arguments.length?b[a||"page"]:b};a.attr=function(a){return 0<arguments.length?c[a||"page"]:b};a.setAttr=function(a,b){c[a||"page"]=b};a.clear=function(a){if(0<arguments.length){var c=b,d=a||"page";try{delete c[d]}catch(k){c[d]=void 0}}else b={}};a.add=function(a,c){var d;a&&(c=c||"page",(d=b[c])||(d=b[c]=[]),D(a)?b[c]=d.concat(a):
M(d,a))};a.set=function(b,c){a.clear(c);a.add(b,c)}}function vc(){function a(){var a;if(a=c.get("ioamplusdata")){var b=c.get("ioamplusttl");if(R(b)&&b>O())return a}}var b=this;Aa||(Aa=new yb(1));var c=Aa.supported?Aa:void 0;b.get=function(d,e,f){var k=p.iom;if(!k)return f=f||0,5>=++f&&K(function(){b.get(d,e,f)},2E3),!1;if(!c||!v(k.gp))return!1;var g=a();!g&&e&&k.gp();var h=Ub(function(){(g=g||a())?(h&&p.clearInterval(h),d(g)):e||h&&p.clearInterval(h)},1E3);return!0}}function wc(){this.trackErrors=
this.trackScroll=this.trackPagePerf=this.logFlash=this.logClientInfo=!0;this.visitTimeout=1800}function xc(a,b){function c(){var a=ka.get();return a&&L(a,"pre")}function d(a){Ba||(Ba=[]);M(Ba,a)}function e(){var a;Ca=0;if(Ba){for(a=0;a<Ba.length;a++){var b=Ba[a];v(b)&&b()}Ba=void 0}}function f(a,b,c){var d=b;if(d){if(!w(d)){if(v(d))return d;if(D(d)){var e=[];for(b=0;b<d.length;b++)M(e,f(a,d[b],c));return e}return f(a,void 0,c)}}else b=ba?ba+".":"",d=b+c;return a+"://"+d+"/wwa.gif"}function k(a,b){var c=
{};var d=new Va(a.get("_wwao"));d.v=void 0;if(b){Ja(B,"trackPagePerf",10,c)&&ka.vis()&&(d.tp=c.value);Ja(B,"trackClicks",10,c)&&(d.tc=c.value);Ja(B,"trackScroll",10,c)&&(d.ts=c.value);Ja(B,"trackErrors",10,c)&&(d.te=c.value);if(Ja(B,"trackAdb",100,c)){var e=c.value;(new ac).check(function(a){ab("$adb",!!a,Ka(e))})}b=Qa(yc,(ba||"").toLowerCase());sa(B,"trackIOPD",b)&&(new vc).get(function(a){ab("$iopd",a)},!0);a.set("_wwao",d,!0)}return d}function g(){var a;if(!(a=Da)){if(!Da){Da=1;sa(B,"logClientInfo",
void 0)&&Ma&&(Aa=(new $b(B)).collect());if(!B.domain){a=u.location.hostname;var b=ob(a,".");1<b&&L(a,"www")?a=y(a,a.indexOf(".",0)):1===b&&"."!==a.charAt(0)&&(a="."+a);B.domain=a}G=new Gb(B);J=new Tb(B);Ma||(J.enabled=!1);J.load();b=J.get;a=J.set;J.cleanup();var c=G.ref;A(c)||"-"===c||"(self)"===c?bb=void 0:(bb=new Eb(c,2,Ea),c=new Eb(u.location.href,0,Ea),"c"===c.gettype()&&(bb=c));c=B.xdt||{};if(c.asTarget||B.xdtEnabled||c.xi)if((c=c.xi||Ra)||(c=u.location,c=jb(c.hash)||jb(c.search)||jb(c.query)),
!A(c)){b:{if(w(c)&&L(c,"xi.")){var d=c.split(".");c=d.length;if(2<c){var e=d[1].split("-");if(3<e.length){var g=N(e[0]);var h=e[1]+"-"+e[2];e=Ia(e[3],36,void 0);var m=X()-Ia(d[2],36,void 0);if(1===g&&e===Cb(h)&&0<=m&&120>=m){h=pb(h,"-");h=parseInt(""+Ia(h[0],36,void 0)+Ia(h[1],36,void 0));if(3<c&&(e=d[3].split("-"),1<e.length)){var l=N(e[0]);var n=[1800*Ia(e[1],36,void 0)]}d={id:h,c:l,ti:n,at:"src_wxi"};break b}}}}d=void 0}Pa={asTarget:1};d&&ib()&&(U.$page=U.$action=U.$download=U.$outlink=p)}c=b("_wwau");
da=new Vb(d||c);n=b("_wwas");l=b("_wwav");h=b("_wwar");g=b("_wwao");A(n)?(new Db(Ea),a("_wwas",Ea),b=1,l=void 0):(new Db(n),A(l)?b=1:(b=B.visitTimeout||1800,w(l)&&(l=ha(l)),b=l.le&&N(l.le)+b<Ea));n=(c?"u":"")+(l?"v":"")+(n?"s":"")+(g?"o":"")+(h?"r":"")+(d?"x":"");J.set("_col",n?n:void 0);Na=new Wb(b?void 0:l,Ea);b&&(d||da.addVisit(Ea),bb&&a("_wwar",bb));(b||d)&&a("_wwau",da);a("_wwav",Na);ea=T.cookieEnabled;!1===ea&&a("_coe",0);ma(B);fb=sa(B,"debugMode",void 0);d="sandbox"===B.environment;a=(a=u.location.protocol)&&
L(a,"https")?"https":"http";fb?d=a=(new bc).log:d?(d=f(a,"wa-sandbox.wipe.de"),a=f(a,"wpt-sandbox.wipe.de")):(d=f(a,B.logTarget,"wwa.wipe.de"),a=f(a,B.itemLogTarget,"wpt.wipe.de"));wa.add(d);xa.add(a);ea&&Ma&&(a=$a=k(J,b),b=Ga,a.tp&&(d=N(a.tp),new kc(G.id,d,W("$perf"),b,Pb)),a.tc&&(d=N(a.tc),Ta=new qc(G.id,d,W("$click")),b.on(0,Ta.init,!0)),a.ts&&(d=N(a.ts),Ua=new rc(G.id,d,W("$viewport")),b.on(0,Ua.init,!0)),a.te&&(d=N(a.te),lb=new pc(G.id,d,W("$error"),cb,Qb,B.trackErrors||{})));la&&V();if(a=(Za||
{}).navigation)Xa("nvt",a.type),(a=a.redirectCount)&&Xa("nvrc",a);Sa&&Xa("ipvis",Sa)}a=void 0}return a}function h(){cb.el.length?K(g,1E3):cb.on=g}function m(a,b){return[ca,aa,"t="+O(),G,Aa,J]}function l(a,b){b=b&&w(b)&&L(b,"action");ea?(a=["_wwav"],b||a.push("_wwar")):a=["_coe=0"];a.push("_coo","_col");a=E(J.toMap(a));if(b){if(b=G.attr){var c="page"+Ha("name");b=Q(b,new Va,[c,"type"]);c={};c.attr=b}}else c={},c.attr=new Va(Sb(G.attr,function(a){return"r_attr"===a||"q_attr"===a})),Q(G,c,["ref","chs",
"host","path","query"]);c&&(c=E(c,"&","di",0,1));return[ca,aa,"t="+O(),E({uid:da.getID(),pid:G.id},"&","ctx"),c,a]}function n(){return[ca,aa,"t="+O(),E({uid:da.getID(),pid:G.id},"&","ctx")]}function p(){return[ca,aa,"t="+O(),G,E(Pa,"&","xdt"),E({uid:da.getID(),uat:da.attr,pid:G.id},"&","ctx")]}function t(a){if(F(a)){var b=a.useCookies;var c=a.persistData;if(Da&&J){if(z(b)&&b!==B.useCookies){(J.enabled=b)?(mb=va(mb),J.save()):mb=K(J.removeAll,500);var d=!0}if(z(c)&&c!==B.persistData){J.persist=c;J.save();
var e=!0}}Q(a,B);(d||e)&&ma(B);d&&ab("$coo","uc"+(b?"1":"0"))}}function r(a,b){var c=G?G.id:void 0;b||(b=ka.get(),a=ka.vis());a&&Oa?Oa=va(Oa):(a=a?50:5E3,va(Oa),Oa=K(function(){Da&&q("$vis","page",c,b);Oa=void 0},a))}function q(a,b,c,d,e){var f,g=W(a).log;if(e&&!La(e)&&e.item&&"$page"!==a){var h=ja(e.item);e.then=f=H(e);e.item=void 0;var k=b||"";"$action"!==a&&(k=y(a,1)+":"+k);S().logAction(h,k,void 0,eb({then:function(){g(b,c,d,e)}},e,!1));return!f}return g(b,c,d,e)}function H(a){var b=void 0;if(a){La(a)&&
(a={ctx:a});var c=a.then;var d=a.ctx;!c&&La(d)&&(c=d);c&&(v(c)?b=c:La(c)?(d=c,a=d.href,"_blank"!==d.target&&Ma&&(Wa(d,"a")&&a?b=function(){tb(d)}:Wa(d,"form")&&d.submit&&(b=function(){var a=d,b;(b=u.activeElement)&&Wa(b,"input")&&/^submit$/i.test(b.getAttribute("type"))&&b.name&&b.form===a?(b=sb(a,b.name,b.value),a.submit(),a.removeChild(b)):a.submit()}))):w(c)&&(b=function(){tb(c)}))}return b}function I(a,b,c,d,e){var f,g=!0;if(z(c)){c=na(c,d);if(e){var h=e;var k=eb({},e);k.then=void 0;k.ctx=void 0}for(f in c)d=
f,e=c[d],z(e)||(e="$-"),e!==a[d]&&(a[d]=e,g=q("$attr",b,d,e,h),h=k);return g}}function P(a){gb||(gb=new sc(G.id,W("$pageel")));gb.mon(a)}function V(){la||(la=[]);Da&&!la.evp&&(la.evp=1,Ga.on(0,function(){db(la,function(a){P(a)});la.length=0},!0))}function S(){Fa||(Fa=new tc(W("$item",xa)));return Fa}function Y(a,b){S().setItems(a,b)}function ja(a){return w(a)&&!fa(a,"=")||R(a)?{id:a}:a}function ya(a,b,c){function e(a,b,c,d,e){g();var k=h?Na.addPV():Na.addEv();var l=J.dirty();J.set("_wwav",Na);J.save(l?
void 0:"_wwav");k?f.log(a,b,c,d,e):e&&e();return!e}var f=new ec(a,b,c),h="$page"===a;this.log=function(a,b,c,f){var g;var h=H(f);!a&&La(f)&&(a=f.href||f.action);F(f)&&(f.isInteraction||f.trackRate)&&(g=Q(f,void 0,["isInteraction","trackRate"]));return Ca?(d(function(){e(a,b,c,g)}),!0):e(a,b,c,g,h)};this.toString=function(){return a}}function W(a,b,c){if(a){var d=za[a];d||(d=new ya(a,b||wa,c||U[a]||m),za[a]=d);return d}}function ma(a){var b=!1===a.useCookies?["uc0"]:[];!1===a.persistData&&b.push("pd0");
a=b.join(".");J.set("_coo",a?a:void 0)}function na(a,b){var c={};var d=D(a);if(!A(a)){if(F(a)&&!d)return a;if(d)for(d=0;d<a.length;d++)c[a[d]]=b;else c[a]=b}return c}function oa(a,b){var c,d;if(a&&F(b))for(c in(d=a.attr)||(d=a.attr=new Va),b)d[c]=b[c];return C}function Xa(a,b){a=na(a,b);Ca?d(function(){g();oa(G,a)}):(g(),oa(G,a));return C}function pa(a,b,c){2>arguments.length&&(b="");hb||(hb={});return I(hb,"page",a,b,c)}function ta(){hb=void 0}function ia(a,b,c){2>arguments.length&&(b="");qa||(qa=
{});return I(qa,"user",a,b,c)}function ab(a,b,c){2>arguments.length&&(b="");ra||(ra={});return I(ra,"session",a,b,c)}var C=this,ua,Ma,aa=new Va({v:"1.15.5"}),ba=a,ca=new fc(ba),za={},Aa,G,bb,J,ea=1,Ea=X(),da,Na,Da,qa,ra,hb,wa=new Ib,xa=new Ib,B=new wc,U={},$a={},Ga,nb=void 0,Pa,Ra,Fa,ka=new kb,Sa=ka.get(),Oa,Ca,Ba,Ta,Ua,gb,la,lb,mb;b&&t(b);(function(){var a;if(!ua){Ma="file:"!==u.location.protocol;U.$attr=U.$perf=U.$click=U.$viewport=U.$pageel=U.$error=U.$vis=n;U.$item=l;wa.enabled=xa.enabled=Ma;
Ga=new Bb;nb=new Xb(function(){g();return da},function(a){fb&&q("$debug","xdt:trd_wxi="+a)});if((a=B.xdt)&&a.viaMessage){nb.rqxi(function(a){Ra=a;fb&&q("$debug","xdt:asg_wxi="+a)},a.sourceWindow,a.sourceHost);var b=!0}if(ka.supported)ka.on(Nb,r);if(Ca=c())ka.on(Ob,e,1);else b&&(Ca=!0,K(e,1E3));sa(B,"trackErrors",void 0)&&(lb||(Ca?d(h):h()),a=B.trackErrors&&B.trackErrors.auto,z(a)&&Qb.upd(a));ua=1}})();C.getEventLogger=function(a){return W(a)};C.logPageView=function(a,b){var c,d;if(F(a)){var e=a.name;
(c=a.attr)&&Xa(c);(d=a.customAttr)&&K(function(){pa(d)},10)}else e=a;Fa&&Fa.logView();return q("$page",e,void 0,void 0,b)};C.logAction=function(a,b){return q("$action",a,void 0,void 0,b)};C.logOutboundLink=function(a,b){Wa(a,"a")&&(a=a.href);return q("$outlink",a,void 0,void 0,b)};C.logDownload=function(a,b){Wa(a,"a")&&(a=a.href);return q("$download",a,void 0,void 0,b)};C.logError=function(a){sa(B,"trackErrors",void 0)&&(w(a)?a={message:a}:a||(a={}),cb.oe(a),lb||(Ca?d(h):h()))};C.setOptions=t;C.newPage=
function(){var a=G.attr;G=new Gb(B);G.attr=a;ta()};C.setPageAttr=Xa;C.resetPageAttr=function(){G.attr=void 0};C.setCustomPageAttr=pa;C.resetCustomPageAttr=ta;C.monitorPageElement=function(a){V();gb?P(a):M(la,a)};C.setSessionAttr=ab;C.clearSessionAttr=function(a){return ab(a,void 0)};C.setUserAttr=ia;C.clearUserAttr=function(a){return ia(a,void 0)};C.setUID=function(a,b){ia("$uuid",a,b)};C.xdt=nb;C.si=function(){return Da?da.getSI(Na.ti):""};C.setPageItem=C.setPageItems=Y;C.logItemView=function(a,
b,c){S().logView(a,b,void 0,c)};C.logItemAction=C.logEntryAction=function(a,b,c){(a=ja(a))&&S().logAction(a,b,void 0,c)};C.setPageEntry=C.setPageEntries=function(a,b){if(w(a)&&!fa(a,"=")||R(a))a={id:a};Y(a,b)};C.setEntryContext=function(a){if(w(a)&&Fa){var b=Fa.buf;var c=b.get(void 0);b.set(c,a);b.clear(void 0)}}}var u=document,p=window,T=navigator,I=p.screen||null,zc=Object.prototype,Fb=void 0,aa=[],Pb=(new Date).getTime(),Jb,qb=zc.hasOwnProperty,ca,Ga,ba,fb,yc=["tb","oe","oe-mobil","gs"],ia,Aa,
wa,Za=ub(p,"performance"),cb=new Lb,Qb=new Mb(cb.oae,!0),Nb=0,Ob=1,$a=2,ea;(function(){Fb=new Zb;var a=new Ab("wwac_id wwac_name wwac_src wwac_med wwac_kw wwac_el".split(" "),"wa");M(aa,a);a=new Ab({utm_id:"wwac_id",utm_campaign:"wwac_name",utm_source:"wwac_src",utm_medium:"wwac_med",utm_term:"wwac_kw",utm_content:"wwac_el"},"utm");M(aa,a);ca="_WA_";Ga="_WWA_";Jb=O()-Pb})();(ba=p[ca]||p[Ga])||(ba=p[ca]=p[Ga]={});eb(ba,{getAnalyzer:function(a,b){var c=a||"";ea||(ea={});(a=ea[c])||(a=ea[c]=new xc(c,
b));return a}})})();
